### ISSUE TITLE
HTTP error codes

### ISSUE THREAD

**Issue by jonasblomqvist** [ntt/eveapi#17]
I just noticed that Odyssey 1.0.1 started using http error codes instead of xml errorcodes to describe problems (patchnotes here) eveapi.py will just crash if a api-key is expired... (http 403 error)

**Comment by notnullxyz** [comment]
This is still open, and I was wondering if it could be closed?
Being a 2013 issue, is is still a problem ?

**Comment by ntt** [comment]
> This is still open, and I was wondering if it could be closed?
> Being a 2013 issue, is is still a problem ?

You do realise the XML API no longer exists right?
